name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_GIT_URL: ${{ secrets.HEROKU_GIT_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Write auth
        run: |
          cat > ~/.netrc <<EOF
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: Git push to Heroku for deploy
        run: |
          git remote add heroku $HEROKU_GIT_URL
          git push heroku main

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use actions/checkout@v2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Handle Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
            ~/.npm
          key: node-deps-${{ hashFiles('package-lock.json') }}
      - name: Install Deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Run Full Build
        run: npm run build
      - name: Run Full KS Build
        run: npm run ks:build
      - name: Run Knapsack Test
        run: npm run ks:test
